### ISSUE TITLE
 Adafruit_SSD1309 folder missing?

### ISSUE THREAD

**Issue by Gopijackson** [lynniemagoo/adafruit-ssd1309-library-node#2]
where is the  Adafruit_SSD1309?

**Comment by lynniemagoo** [comment]
This is a NodeJS library. Did you look in the lib folder?

**Comment by Gopijackson** [comment]
i need cpp code. If it's possible

**Comment by lynniemagoo** [comment]
Then search the adafruit GitHub user.

**Comment by lynniemagoo** [comment]
Here's one project for pico that will likely work. 

Raspberry Pico SSD1309 + GFX Library

**Comment by Gopijackson** [comment]
But,im using ESP32-S3-MINI-1

**Comment by lynniemagoo** [comment]
Sorry. This is what I have.  I know there are other libraries such as UG8 that support this display. I searched web for ssd1309 esp8266 and found this. 

https://ibrahimgunduz34.medium.com/interfacing-2-4-ssd1309-spi-oled-display-with-esp8266-1041734ef4bf

This demo of the SPI model should get you started.

**Comment by Gopijackson** [comment]
ok, thanks for sharing
